Models/ErrorViewModel.cs
using System;

namespace ExLogin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Infra/AcessarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExLogin.Models.Infra
{
    public class AcessarViewModel
    {
        [Key]
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        [Display(Name = "Lembrar de mim?")]
        public bool LembrarDeMim { get; set; }
    }
}

Models/Infra/RegistrarNovoUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExLogin.Models.Infra
{
    public class RegistrarNovoUsuarioViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "E-mail")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage =
            @"A {0} precisa ter ao menos {2} e no máximo
                {1} caracteres de cumprimento", MinimumLength = 6)]
        [Display(Name = "Senha")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirma Senha")]
        [Compare("Password", ErrorMessage =
            @"Os valores informados para SENHA e CONFIRMAÇÃO não são iguais.")]
        public string ConfirmPassword { get; set; }
    }
}

Models/Infra/UsuarioDaAplicacao.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExLogin.Models.Infra
{
    public class UsuarioDaAplicacao : IdentityUser
    {
    }
}

Controllers/HomeController.cs
using ExLogin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExLogin.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InfraController.cs
using ExLogin.Models.Infra;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExLogin.Controllers
{
    [Authorize]
    public class InfraController : Controller
    {
        private readonly UserManager<UsuarioDaAplicacao> _userManager;
        private readonly SignInManager<UsuarioDaAplicacao> _signInManager;
        private readonly ILogger _logger;

        public InfraController(
            UserManager<UsuarioDaAplicacao> userManager,
            SignInManager<UsuarioDaAplicacao> signInManager,
            ILogger<InfraController> logger
            )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Acessar(string returnUrl = null)
        {
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            if (returnUrl == null)
            {
                returnUrl = "/Home/Index";
            }
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        //todo : Montar POST do Acessar
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Acessar(AcessarViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {

                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Senha, model.LembrarDeMim, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("Usuário Autenticado.");
                    return RedirectToLocal(returnUrl);
                }

            }
            ModelState.AddModelError(string.Empty, "Falha na tentativa de login");
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult RegistrarNovoUsuario(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegistrarNovoUsuario(
            RegistrarNovoUsuarioViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new UsuarioDaAplicacao
                {
                    UserName = model.Email,
                    Email = model.Email
                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    _logger.LogInformation("Usuário criado com sucesso");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation("Usuário acesso com a conta criada");
                    return RedirectToLocal(returnUrl);
                }
                AddErrors(result);
            }
            return View(model);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(error.Code, error.Description);
            }
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

        }


        [HttpGet]
        public async Task<IActionResult> Sair()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("Usuário realizou logout");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_LayoutIES.cshtml";
}

<div class="container">
    <div clss="row justify-content-center align-items-center">
        
    </div>
</div>

Views/Infra/Acessar.cshtml
@model ExLogin.Models.Infra.AcessarViewModel

@{
    ViewData["Title"] = "Acessar";
    Layout = "~/Views/Shared/_LayoutIES.cshtml";
}

<div class="card-header text-white bg-secondary text-center h1">Faça seu Login</div>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <section>
            <form asp-route-returnurl="@ViewData["ReturnURL"]" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Senha"></label>
                    <input asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label asp-for="LembrarDeMim">
                            <input asp-for="LembrarDeMim" />
                            @Html.DisplayNameFor(m => m.LembrarDeMim)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Acessar</button>
                </div>
                <div class="form-group">
                    <p>
                        <a asp-action="ForgotPassword">Esqueceu sua senha?</a>
                    </p>
                    <p>
                        <a asp-action="RegistrarNovoUsuario" asp-route-returnurl="@ViewData["ReturnUrl"]">
                            Registrar novo usuário?
                        </a>
                    </p>
                </div>
            </form>
        </section>
    </div>
    <div class="col-md-4"></div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Infra/RegistrarNovoUsuario.cshtml
@model ExLogin.Models.Infra.RegistrarNovoUsuarioViewModel

@{
    ViewData["Title"] = "Registrar Novo Usuario";
    Layout = "~/Views/Shared/_LayoutIES.cshtml";
}

<div class="card-header text-white bg-secondary text-center h1">
    Registrar uma nova conta de usuário
</div>

<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-secondary">Registrar</button>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExLogin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExLogin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ExLogin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutIES.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ExLogin.Models.Infra.UsuarioDaAplicacao> SignInManager
@inject Microsoft.AspNetCore.Identity.UserManager<ExLogin.Models.Infra.UsuarioDaAplicacao> UserManager

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar fixed-top navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="#">

        </a>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">&nbsp;</div>
            <div class="col-12">&nbsp;</div>
            <div class="col-12">&nbsp;</div>
            <div class="col-12">&nbsp;</div>
        </div>

        <div class="row" style="text-align:right;">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                @if (SignInManager.IsSignedIn(User))
                {
                    <div>
                        Olá @UserManager.GetUserName(User), bem-vindo |
                        @Html.ActionLink("Sair", "Sair", "Infra", new { area = "" })
                    </div>
                }
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <nav class="nav flex-column">


                </nav>
            </div>
            <div class="col-10">
                <div class="row">
                    <div class="col-12">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar fixed-bottom" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="#">Sistema</a>
    </nav>
    @RenderSection("Scripts", required: false)
</body>
</html>